### ISSUE TITLE
Shiny app interface fixes

### ISSUE THREAD

**Issue by skylerlewis** [FlowWest/habistat#26]
**High priority:**
- [x] Highlight selected ComID (maddee)
- [x] Add option for total acres instead of SHA/LF (skyler)
   - [ ] Still need to fix some legends and the duration calculation under total acres
- [x] Auto-select streamgage for duration HSI (skyler)
- [ ] Update the duration plotting routine to apply the VL or VF duration curve (skyler)

**lower priority:** 
- [ ] Flowline display/legend cleanup (skyler)
- [x] add leaflet layer toggle (maddee)
- [x]  Add HQT boundary to leaflet (maddee)
- [ ] Add HQT to descriptors in the bottom section (maddee)
- [ ] add aerial basemap layer option to leaflet (maddee)

**Comment by MaddeeRubenson** [comment]
these updates will be done in `26-shiny-app-interface-fixes` branch
